---
ID: "eddac6b5-e48c-481b-b795-ba95d29db238"
Parent: "f31086d8-c2a8-477b-875b-fdcad23ce43c"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/Marketplace/Content Editor/Ribbon/Security
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T141105Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
